# Excercise 01

In [1]:
import numpy as np

def square_matrix_multiply(A, B):
    n = A.shape[0] 
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    return C

In [2]:
A = np.array([[3, 4, 2], [4, 6, 7],[1, 2, 4]])
B = np.array([[6, 4, 2], [8, 2, 3],[1, 3, 4]])

In [3]:
result = square_matrix_multiply(A, B)

In [4]:
print(result)

[[52. 26. 26.]
 [79. 49. 54.]
 [26. 20. 24.]]


**Analysis of Time Complexity**

The time complexity analysis for this algorithm stays consistent with the previous explanation. The algorithm employs three nested loops, iterating through each element of the resulting matrix C. In each iteration, it calculates the dot product of a row in matrix A with a column in matrix B.

In detail:

The outer loop (indexed by i) runs n times, where n represents the size of the matrices.

The middle loop (indexed by j) iterates n times for each iteration of the outer loop.

The inner loop (indexed by k) runs n times for each iteration of the middle loop.

This arrangement results in a total of n * n * n = n^3 scalar multiplications being executed.

Consequently, the time complexity of this algorithm is denoted as O(n^3).

The rationale behind this assessment remains consistent with the earlier explanation. The algorithm's structure comprises three nested loops, each iterating n times, thereby leading to a cubic time complexity. Each loop iteration entails n scalar multiplications, cumulatively amounting to n^3 scalar multiplications. Consequently, the time complexity indeed stands at O(n^3).

### Implement

In [6]:
import time

In [7]:
nestedlist1 = np.random.rand(10, 10).tolist()

In [8]:
nestedlist2 = np.random.rand(10, 10).tolist()

In [9]:
nestedlist3 = np.random.rand(100, 100).tolist()

In [10]:
nestedlist4 = np.random.rand(100, 100).tolist()

In [11]:
def square_matrix_multiply(A, B):
    n = len(A)
    C = [[0 for i in range(n)] for i in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

In [12]:
start_time = time.time()
square_matrix_multiply(nestedlist1, nestedlist2)
end_time = time.time()
execution_time = end_time - start_time
print("Execution time:", execution_time, "seconds")

Execution time: 0.000946044921875 seconds


In [13]:
start_time = time.time()
square_matrix_multiply(nestedlist3, nestedlist4)
end_time = time.time()
execution_time = end_time - start_time
print("Execution time:", execution_time, "seconds")

Execution time: 0.35797929763793945 seconds


### Comparing execution times (in seconds) for custom vs. built-in multiplication:

In [14]:
def square_matrix_multiply(A, B):
    n = len(A)
    C = [[0 for i in range(n)] for i in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

def generate_random_matrix(n):
    return [[np.random.rand() for _ in range(n)] for _ in range(n)]

def measure_custom_time(matrix_size):
    A = generate_random_matrix(matrix_size)
    B = generate_random_matrix(matrix_size)
    
    start_time = time.time()
    square_matrix_multiply(A, B)
    end_time = time.time()
    
    return end_time - start_time

def measure_builtin_time(matrix_size):
    A = np.random.rand(matrix_size, matrix_size)
    B = np.random.rand(matrix_size, matrix_size)
    
    start_time = time.time()
    np.dot(A, B)
    end_time = time.time()
    
    return end_time - start_time

matrix_sizes = [10, 50, 100, 200, 500]

print("Comparing execution times (in seconds) for custom vs. built-in multiplication:")
print("{:<10} {:<15} {:<15}".format("Matrix Size", "Custom Time", "Built-in Time"))
for size in matrix_sizes:
    custom_time = measure_custom_time(size)
    builtin_time = measure_builtin_time(size)
    print("{:<10} {:<15.6f} {:<15.6f}".format(size, custom_time, builtin_time))

Comparing execution times (in seconds) for custom vs. built-in multiplication:
Matrix Size Custom Time     Built-in Time  
10         0.001002        0.018447       
50         0.043015        0.000000       
100        0.238083        0.002000       
200        2.158756        0.002033       
500        32.722635       0.007995       


### Multiply more than two matrices / perform other operations on matrices

In [16]:
def multiply_multiple_matrices(matrices):
    result = matrices[0]
    for i in range(1, len(matrices)):
        result = np.dot(result, matrices[i])
    return result

def measure_multiple_matrices_time(matrix_size, num_matrices):
    matrices = [np.random.rand(matrix_size, matrix_size) for _ in range(num_matrices)]
    
    start_time = time.time()
    multiply_multiple_matrices(matrices)
    end_time = time.time()
    
    return end_time - start_time

def measure_custom_multiple_matrices_time(matrix_size, num_matrices):
    matrices = [generate_random_matrix(matrix_size) for _ in range(num_matrices)]
    
    start_time = time.time()
    result = matrices[0]
    for i in range(1, len(matrices)):
        result = square_matrix_multiply(result, matrices[i])
    end_time = time.time()
    
    return end_time - start_time

num_matrices = 3

print("\nComparing execution times (in seconds) for custom vs. built-in multiplication of {} matrices:".format(num_matrices))
print("{:<10} {:<15} {:<15}".format("Matrix Size", "Custom Time", "Built-in Time"))
for size in matrix_sizes:
    custom_time = measure_custom_multiple_matrices_time(size, num_matrices)
    builtin_time = measure_multiple_matrices_time(size, num_matrices)
    print("{:<10} {:<15.6f} {:<15.6f}".format(size, custom_time, builtin_time))


Comparing execution times (in seconds) for custom vs. built-in multiplication of 3 matrices:
Matrix Size Custom Time     Built-in Time  
10         0.001084        0.001062       
50         0.077531        0.000000       
100        0.577909        0.002001       
200        4.467828        0.003000       
500        67.795220       0.012995       


# Exercise 02

In [21]:
def split_matrix(A, n):
    A11 = [row[:n] for row in A[:n]]
    A12 = [row[n:] for row in A[:n]]
    A21 = [row[:n] for row in A[n:]]
    A22 = [row[n:] for row in A[n:]]
    return A11, A12, A21, A22


def matrix_add(A, B):
    n = len(A)
    return [[A[i][j] + B[i][j] for j in range(n)] for i in range(n)]


def combine_matrix(A, B, C, D, n):
    top = [A[i] + B[i] for i in range(n)]
    bottom = [C[i] + D[i] for i in range(n)]
    return top + bottom


def square_matrix_multiply_recursive(A, B):
    n = len(A)
    if n == 1:
        return [[A[0][0] * B[0][0]]]
    else:
        mid = n // 2
        A11, A12, A21, A22 = split_matrix(A, mid)
        B11, B12, B21, B22 = split_matrix(B, mid)

        # recursive
        C11 = matrix_add(square_matrix_multiply_recursive(A11, B11),
                         square_matrix_multiply_recursive(A12, B21))
        C12 = matrix_add(square_matrix_multiply_recursive(A11, B12),
                         square_matrix_multiply_recursive(A12, B22))
        C21 = matrix_add(square_matrix_multiply_recursive(A21, B11),
                         square_matrix_multiply_recursive(A22, B21))
        C22 = matrix_add(square_matrix_multiply_recursive(A21, B12),
                         square_matrix_multiply_recursive(A22, B22))

        # combining quarters
        C = combine_matrix(C11, C12, C21, C22, mid)
        return C

***Algorithm Description***

> 01. **Recursiveness:**
- **Recursive Nature:**  
  The algorithm repetitively splits the matrices into smaller segments until they reach a minimal size, typically 1x1, where a direct multiplication operation can be executed.

02. **Divide-and-Conquer:**
- **Divide:**  
  Initially, the algorithm divides the input matrices into four equal-sized quarters, setting the stage for further processing.
- **Conquer:**  
  It subsequently tackles each submatrix pair recursively, multiplying them until they reach the base case.
- **Combine:**  
  After recursive multiplication, the algorithm combines the results from individual submatrices to generate the final product.





   
***Implementation***


> The translation of the pseudocode into Python functions primarily involves direct mapping, albeit with some complexity in handling matrix splits and combines, necessitating careful index management.




***Complexity Analysis***



> - **Base Case:**
Multiplying 1x1 matrices involves one operation, hence O(1) time complexity.
- **Divide Step:**  
  Dividing matrices into quarters necessitates copying elements, taking O(n^2) time.
- **Conquer Step:**  
  The recursive multiplication of submatrices involves eight recursive calls, each dealing with matrices of size n/2, leading to a per-call time complexity of T(n/2).
- **Combine Step:**  
  Combining submatrices involves element-wise addition, taking O(n^2) time.
- **Overall:**  
  The overall time complexity is deduced as O(n^3) from the recurrence relation T(n) = 8T(n/2) + O(n^2), reflecting the need for additions and multiplications at each recursion level within the divide-and-conquer framework. Despite its recursive nature, the divide-and-conquer approach helps manage the problem by breaking it into smaller, more manageable subproblems.


In [22]:
A = np.random.rand(128,128)
B = np.random.rand(128,128)

In [23]:
start_time = time.time()
square_matrix_multiply_recursive(A,B)
end_time = time.time()
execution_time = end_time - start_time
print("Execution time:", execution_time, "seconds")

Execution time: 7.632548093795776 seconds


In [24]:
start_time = time.time()
square_matrix_multiply(A,B)
end_time = time.time()
execution_time = end_time - start_time
print("Execution time:", execution_time, "seconds")

Execution time: 1.4195423126220703 seconds


# Excercise 03

In [25]:
def matrix_sub(A, B):
    n = len(A)
    return [[A[i][j] - B[i][j] for j in range(n)] for i in range(n)]


def strassen_matrix_multiply(A, B):
    n = len(A)
    if n == 1:
        return [[A[0][0] * B[0][0]]]
    else:
        # Splitting and recombining matrices
        mid = n // 2
        A11, A12, A21, A22 = split_matrix(A, mid)
        B11, B12, B21, B22 = split_matrix(B, mid)

        # Strassen's multiplication operations
        M1 = strassen_matrix_multiply(matrix_add(A11, A22), matrix_add(B11, B22))
        M2 = strassen_matrix_multiply(matrix_add(A21, A22), B11)
        M3 = strassen_matrix_multiply(A11, matrix_sub(B12, B22))
        M4 = strassen_matrix_multiply(A22, matrix_sub(B21, B11))
        M5 = strassen_matrix_multiply(matrix_add(A11, A12), B22)
        M6 = strassen_matrix_multiply(matrix_sub(A21, A11), matrix_add(B11, B12))
        M7 = strassen_matrix_multiply(matrix_sub(A12, A22), matrix_add(B21, B22))

        # Combining results
        C11 = matrix_add(M1, M4)
        C11 = matrix_sub(C11, M5)
        C11 = matrix_add(C11, M7)
        C12 = matrix_add(M3, M5)
        C21 = matrix_add(M2, M4)
        C22 = matrix_add(M1, M3)
        C22 = matrix_sub(C22, M2)
        C22 = matrix_sub(C22, M6)

        C = combine_matrix(C11, C12, C21, C22, mid)
        return C

***Reflection on Matrix Operations Complexity***


> Matrix multiplication typically involves more complex operations than addition and subtraction. Multiplying two matrices involves the scalar product of rows and columns, resulting in more computational steps compared to addition or subtraction, which only requires adding or subtracting corresponding elements.



***Complexity Analysis of Strassen Algorithm***

**Base Case:**The base case remains the same as the recursive algorithm in Exercise 2, involving a single multiplication operation, hence O(1).
**Divide Step:**Splitting matrices into quarters takes O(n^2) time, similar to the recursive algorithm.
**Conquer Step:**Strassen's algorithm performs seven recursive multiplications of matrices of size n/2 × n/2. Each of these recursive calls deals with matrices of half the size of the original matrices, leading to a time complexity of T(n/2) per call.
**Combine Step:**After the recursive multiplications, there are additional steps (S1 to S10) involving additions and subtractions, totaling 10 extra operations.
The final step combines the submatrices into the resulting matrix C, which also involves additions and subtractions.
**Overall Complexity:**The recurrence relation for Strassen's algorithm is T(n) = 7T(n/2) + O(n^2), as there are seven recursive calls each dealing with matrices of size n/2 × n/2; Using the Master Theorem or other methods, the overall time complexity is deduced as O(n^log2(7)) ≈ O(n^2.81); Compared to the naive recursive algorithm, Strassen's algorithm reduces the number of recursive multiplications but introduces additional overhead due to extra addition and subtraction operations.

*[Adaptation and Explanation of Changes]*

The implemented code adapts the Strassen algorithm by incorporating the splitting, combining, and recursive multiplication operations. Instead of eight recursive multiplications as in Exercise 2, Strassen's algorithm performs seven recursive multiplications. Additionally, it includes extra steps (S1 to S10) for additions and subtractions before the recursive multiplications and after to calculate the final quarters of matrix C. These changes affect the overall time complexity, reducing the number of recursive multiplications while introducing extra overhead for additional operations.

Overall, Strassen's algorithm optimizes matrix multiplication by reducing the number of recursive multiplications, which leads to improved performance for large matrices. However, the algorithm's effectiveness depends on various factors, such as the size of the matrices and the efficiency of the implementation.